### ISSUE TITLE
Attribution Lomuto partition

### ISSUE THREAD

**Issue by orlp** [RedBedHed/blipsort#1]
Hi, I've noticed that you do mention me and my blog post on Lomuto partitioning, but I have a few nitpicks I'd like to see fixed:

- You credit me by name, but not Lukas Bergdoll. I think it's important to mention him as well, we are co-authors of the partition. While I did make the final structure of the algorithm he was the one that did all the experimental work, and it was his idea to (re-)investigate Lomuto-style partitions in the first place to find a bunch of well-performing prototypes that lead to the final design. 
- My name is Orson Peters, not Orson Peter. In a couple places you refer to `Orson Peter's <X>` instead of `Orson Peters' <X>`.
- ~~You refer to my blog post but don't link it. I'd love it if you'd [link it](https://orlp.net/blog/branchless-lomuto-partitioning/).~~ Oops I see you link it at the bottom.

**Comment by RedBedHed** [comment]
Hi, Orson! 

I have an appointment this afternoon but will make these corrections ASAP. Sincere apologies for misspelling your name.

Ellie

**Comment by RedBedHed** [comment]
Ah, okay, it turned out to be a very quick fix. :) Please let me know if I missed anything.

Ellie

**Comment by orlp** [comment]
All good 👍
